#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_ora = env_modules.Clone()

# Godot source files
env_ora.add_source_files(env.modules_sources, "*.cpp")
